version: '1'

services:

  # contact-support-team service
  contact-support-team:
      image: contact-support-team:1.0.0
      container_name: contact-support-team
      ports:
        - "8000:8000"
      depends_on:
        - mongodb-contact-support-team 
      environment:
        - MONGODB_HOST=mongodb-contact-support-team 
        - MONGODB_PORT=27017
        - MONGODB_DATABASE=contact_support # MongoDB will create the database when it contains data.

  mongodb-contact-support-team:
    image: mongo
    container_name: mongodb-contact-support-team
    volumes:
      - mongodb_contact_support_data:/data/db  # Volume name and location inside the container 


  # shipping-and-handling service 
  shipping-and-handling:
    image: shipping-and-handling:1.0.0
    container_name: shipping-and-handling
    ports:
      - "8080:8080"
    depends_on:
      - mongodb-shipping
    environment:
      - MONGODB_URI=mongodb://mongodb-shipping:27017  

  mongodb-shipping:
    image: mongo
    container_name: mongodb-shipping
    ports:
      - "27020:27017" # Avoid conflicts if multiple MongoDB services exist. each can be exposed on a different port on the host while using 27017 internally.
    volumes:
      - mongodb_shipping_data:/data/db
  

  # product-catalog service     
  product-catalog:
    image: product-catalog:1.0.0
    container_name: product-catalog
    ports:
      - "3001:3001"
    depends_on:
      - mongodb-product-catalog

    environment:
      - MONGODB_HOST=mongodb-product-catalog
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=product_catalog     
  
  mongodb-product-catalog:
    image: mongo
    container_name: mongodb-product-catalog
    volumes:
      - mongodb_product_catalog_data:/data/db
  

  order-management:
    image: order-management:1.0.0
    container_name: order-management
    depends_on:
      - mongodb-order-management
    ports:
      - "9090:9090"
    environment:
      - PRODUCT_INVENTORY_API_HOST=http://product-inventory
      - PRODUCT_CATALOG_API_HOST=http://product-catalog
      - SHIPPING_HANDLING_API_HOST=http://shipping-and-handling
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-order-management:27017/order_management

  mongodb-order-management: # mongo will use container port 27017
    image: mongo
    container_name: mongodb-order-management
    volumes:
      - mongodb_order_management:/data/db